DROP TABLE IF EXISTS author;

CREATE TABLE author (
    id   BIGINT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    login  VARCHAR(255) NOT NULL UNIQUE
);

