#Wed Nov 08 12:35:31 AZOT 2023
micronaut:
  application:
    name: blog
flyway:
  datasources:
    default:
      enabled: true
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db
    dialect: MYSQL
    username: root
    password: 123
    driverClassName: com.mysql.cj.jdbc.Driver

jpa:
  default:
    entity-scan:
      packages: 'com.andrecastrosousa.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true